apiVersion: v1
kind: Service
metadata:
  name: k8s-01
spec:
  selector:
    app: k8s-01
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-01 
  template:
    metadata:
      labels:
        app: k8s-01
    spec:
      containers:
        - name: k8s-01
          image: laksiriben/k8s-test-01:1.0.1
          ports:
            - containerPort: 3000
          imagePullPolicy: Always